services:

  db:
    image: postgres
    container_name: http-calendar-db
    networks:
      - db-net
    environment:
      PGUSER: ${POSTGRES_USER}
      PGDATABASE: ${POSTGRES_DB}
      POSTGRES_PASSWORD: ${POSTGRES_PASS}
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}" ]
      interval: 10s
      retries: 5
      start_period: 30s
      timeout: 10s
    ports:
      - "${POSTGRES_PORT}:5432"
    volumes:
      - ./migrations/create_db.sql:/docker-entrypoint-initdb.d/create_database.sql

  migrate:
    image: migrate/migrate
    networks:
      - db-net
    volumes:
      - ./migrations:/migrations
    command: [ "-path", "/migrations", "-database",  "postgres://${POSTGRES_USER}:${POSTGRES_PASS}@db:5432/${POSTGRES_DB}?sslmode=disable", "up"]
    links:
      - db
    depends_on:
      db:
        condition: service_healthy

networks:
  db-net:
    driver: bridge